### ISSUE TITLE
Making facilmap easily installable on yunohost

### ISSUE THREAD

**Issue by eauchat** [FacilMap/facilmap#116]
Hello, first thanks again for the great tool that facilmap is.

I remember having a discussion with you about it, but I wonder if you're still interested in making facilmap easily installable on [yunohost](https://yunohost.org/) servers.
It would be a great way to make facilmap easily accessible to many administrators that care about decentralization.

I would love to contribute to doing this, but I'm still not competent in packaging yunohost apps, nor on how facilmap works exactly. But I'd definitely be willing to contribute if you're motivated in making this happen.

Any thoughts on that? :)

**Comment by cdauth** [comment]
Just to give an update to this, when you reported it I gave it a try to set this up, but I found it quite complicated to do, particularly because of the fact that I don't use yunohost myself, so it would take a lot of time for me to try it out.

Maybe I will give it another try at some point, but I would be really happy if someone who has more experience with yunohost would take case of this.

**Comment by eauchat** [comment]
I started packaging yunohost apps, and I agree that it's not the simplest thing at the moment.
Maybe I could give a try to packaging facilmap. I have some knowledge of yunohost, but I'm missing the knowledge of facilmap. I never really installed it from scratch, and I stopped selfhosting it because of maintenance issues.

I'm up for trying to make the facilmap yunohost package, but I don't know anything about the type of databases you use, and that is kind of what blocks me from even trying. If I'm not wrong, the rest of the app is just a nodejs server, no? If it's the case, that part shouldn't be a problem.

If you or someone else with knowledge on the parts I'm missing is motivated to participate to making the package, to fill the knowledge I'm missing, I'd be up for trying to do it collaboratively.

Also, from what I understood, you're working at a new facilmap version? Maybe it would be worth working directly at packaging that new version, no?

**Comment by cdauth** [comment]
It makes sense to work with the new FacilMap version. The code is currently on the "typescript" branch of this repository, but will be moved to the master branch soon. I still have to update the READMEs though, so they are outdated.

FacilMap is a simple Node.js app that uses a mysql/mariadb database. The steps to set it up:
1. Run `yarn install` and then `yarn build` in the main directory of FacilMap
2. Copy `config.env.example` to `config.env` and add the configuration values. For Yunohost, the following values probably need to be set:
    * The `HOST` should probably be `127.0.0.1`, as FacilMap should be reachable only through the webserver, not directly
    * The `PORT` needs to be set to something unique so that it doesn't collide with other apps. Not sure how that works on Yunohost.
    * The `DB_*` variables need to be set to the database configuration.
    * The `*_TOKEN` and `USER_AGENT` variables should be configurable, so that the administrator who is installing FacilMap could set them.

FacilMap can be started by running `yarn server` in the `server` directory. It will automatically set up its database layout and so on.

Permission-wise, FacilMap does not need write access to any of its files, except the `server/cache` subdirectory.

All the setup steps are also done in the [Dockerfile](https://github.com/FacilMap/facilmap2/blob/typescript/Dockerfile), maybe that is of any help.

**Comment by eauchat** [comment]
Ok, then I'll give it a try. Hope that's useful to someone and to facilmap!

Looking at your instructions and the config file, it should be pretty straightforward (thanks to yunohost taking care of the database aspects).

I'll start right away then. Two things though:
- Are all the tokens in the config file optional, or not? If not, which ones are mandatory?
- While developing the package, I'll hack a bit and make my own zip of the typescript branch, but when it's ready, the package will need a proper release zip available from the repository's releases page. When do you plan having the typescript branch merged to master and released?

**Comment by cdauth** [comment]
I think I'll make `OSR_TOKEN` and `MAPBOX_TOKEN` mandatory, since routing wouldn't work at all without them. The other tokens can be optional.

I'm planning to release the new version in a few weeks, once some more extensive testing has been done and I've fixed all the bugs. I haven't decided a fixed date yet. I'll use git tag `v3.0.0` for the first release, so it will be available as https://github.com/FacilMap/facilmap2/archive/refs/tags/v3.0.0.zip. For now you can download the ZIP of the typescript branch here: https://github.com/FacilMap/facilmap2/archive/refs/heads/typescript.zip

**Comment by eauchat** [comment]
Ok cool for the zip and the tokens.
One question about the database port. Can it be left empty, or should it be specified somehow? I don't know how mysql is setup on yunohost, but it's most probably a standard debian setup.

**Comment by eauchat** [comment]
One more note about tokens. If I make them mandatory in the package, it means that people will not be able to even start installing facilmap without providing them, so they can't even test it a bit. Do you confirm it's better this way for you?

Also, does facilmap supports being installed in a subpath (like https://domain.tld/facilmap/ for example).

Sorry for asking many questions, but I think it's better to get started with a quality package directly, and one that you also consider good.

**Comment by cdauth** [comment]
To respond to your questions, it sounds like a good idea to make it possible to start FacilMap without the tokens. So I'll make sure that the UI shows proper error messages in that case.

I haven't tested FacilMap in a sub-folder yet, but I can do it. If it doesn't work, I will fix it before releasing 3.0.0.

**Comment by eauchat** [comment]
I tried the NODE_OPTIONS you proposed, but the problem doesn't seem to resolve.
But there is definitely something weird going on. Yunohost stores logs of apps installation, and the log of facilmap end up weight 1.5G. It doesn't display properly and show an endless amount of "*******".
I wonder if something like yarn, webpack, some node library or facilmap itself would have some kind of terminal display "spinner" that outputs things that end up filling the log file with gigs of *.
I don't know, I don't really understand. I will also report to the yunohost folks themselves to see if someone has an idea over there, just to keep you informed as well.

**Comment by cdauth** [comment]
FYI: The v3 beta is now on the master branch and I renamed the repository from `facilmap2` to `facilmap`. So the download link for the zip is now https://github.com/FacilMap/facilmap/archive/refs/heads/master.zip.

**Comment by eauchat** [comment]
Hey, thanks for the corrections on the package, I merged them and tested it.

I'm still having the same issue though while trying to install on the testing VM I'm using that has 512MB of RAM. I use this for test because yunohost is meant to be able to run also on low power devices. Is it enough to run facilmap?

I also tried testing it on the same VM but giving it 1GB or RAM. It seems to be getting further, but still eventually gets into memory issues apparently. These are the logs I'm getting (not so different from the ones before).
```
Info: [################+...] > Building node dependencies...
Warning: warning Skipping preferred cache folder "/home/facilmap/.cache/yarn" because it is not writable.
Warning: warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-997".
Warning: warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
Warning: warning " > facilmap-leaflet@3.0.1" has unmet peer dependency "leaflet@x".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-frontend > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-frontend > popper-max-size-modifier@0.2.0" has unmet peer dependency "@popperjs/core@^2.2.0".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-leaflet > leaflet-auto-graticule@1.0.9" has unmet peer dependency "leaflet@x".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-leaflet > leaflet-freie-tonne@1.0.5" has unmet peer dependency "leaflet@x".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-leaflet > leaflet-highlightable-layers@1.0.9" has unmet peer dependency "leaflet@x".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-leaflet > leaflet.markercluster@1.5.0" has unmet peer dependency "leaflet@^1.3.1".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-utils > linkifyjs@3.0.0-beta.3" has unmet peer dependency "react@>= 0.14.0".
Warning: warning "workspace-aggregator-f369bc01-28ad-4ceb-9826-e354810d11a5 > facilmap-utils > linkifyjs@3.0.0-beta.3" has unmet peer dependency "react-dom@>= 0.14.0".
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: warning Skipping preferred cache folder "/home/facilmap/.cache/yarn" because it is not writable.
Warning: warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-997".
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: warning Skipping preferred cache folder "/home/facilmap/.cache/yarn" because it is not writable.
Warning: warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-997".
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: warning Skipping preferred cache folder "/home/facilmap/.cache/yarn" because it is not writable.
Warning: warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-997".
Warning: warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/facilmap/.yarn"
Warning: <--- Last few GCs --->
Warning: [10620:0x4767fd0]    46530 ms: Scavenge (reduce) 491.3 (494.1) -> 490.8 (495.1) MB, 49.1 / 0.0 ms  (average mu = 0.162, current mu = 0.057) allocation failure
Warning: [10620:0x4767fd0]    46673 ms: Scavenge (reduce) 491.4 (494.1) -> 491.0 (495.3) MB, 55.3 / 0.0 ms  (average mu = 0.162, current mu = 0.057) allocation failure
Warning: [10620:0x4767fd0]    46768 ms: Scavenge (reduce) 491.7 (497.3) -> 491.3 (498.1) MB, 65.8 / 0.0 ms  (average mu = 0.162, current mu = 0.057) allocation failure
Warning: <--- JS stacktrace --->
Warning: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Warning:  1: 0xa04200 node::Abort() [webpack]
Warning:  2: 0x94e4e9 node::FatalError(char const*, char const*) [webpack]
Warning:  3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
Warning:  4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
Warning:  5: 0xd34395  [webpack]
Warning:  6: 0xd34f1f  [webpack]
Warning:  7: 0xd42fab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
Warning:  8: 0xd46b6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
Warning:  9: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
Warning: 10: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
Warning: 11: 0x1401219  [webpack]
Warning: Aborted
Warning: error Command failed with exit code 134.
Warning: error Command failed with exit code 134.
Error: Unable to install facilmap: An error occurred inside the app installation script
Info: The operation 'Install the 'facilmap' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20210413-231055-app_install-facilmap --share' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG -
Info: WARNING - <--- JS stacktrace --->
Info: DEBUG -
Info: WARNING - FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Info: WARNING -  1: 0xa04200 node::Abort() [webpack]
Info: WARNING -  2: 0x94e4e9 node::FatalError(char const*, char const*) [webpack]
Info: WARNING -  3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
Info: WARNING -  4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
Info: WARNING -  5: 0xd34395  [webpack]
Info: WARNING -  6: 0xd34f1f  [webpack]
Info: WARNING -  7: 0xd42fab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
Info: WARNING -  8: 0xd46b6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
Info: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Info: WARNING -  9: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
Info: WARNING - 10: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
Info: WARNING - 11: 0x1401219  [webpack]
Info: WARNING - Aborted
Info: WARNING - error Command failed with exit code 134.
Info: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Info: WARNING - error Command failed with exit code 134.
Info: DEBUG - + ynh_exit_properly
```

**Comment by cdauth** [comment]
I can imagine that the bundling and checking of the TypeScript types takes quite a lot of memory, but running FacilMap should take much less.

I checked the production instance of FacilMap, which runs on a server with 16 GB of RAM, and it says that FacilMap takes about 450 MB of RAM. However, I don't think this is an indicator how much it will use on another system, it might be less if less is available. For example, on my system Etherpad (which also runs on Node.js) uses 1 GB of RAM, and I guess on your system it uses much less.

I will invest some time to publish prebuilt bundles in the next days (that was my plan anyways) and then open another pull request that will use those.

**Comment by eauchat** [comment]
Heyyo, following your improvements in the facilmap_ynh repo, I made some additional corrections (not to things you improved but to the rest) and I tried to setup the package for publishing it.

I have tested facilmap locally and the package works fine for me.
Then I sent it to the yunohost CI for testing, and it seems not so happy and complains about many things, but seems to be either just one same issue, or even just a bug with the way the CI does things. [This](https://ci-apps-dev.yunohost.org/ci/job/1798) are the not very successful tests in the CI and [here](https://ci-apps-dev.yunohost.org/ci/job/1799) is another attempt after the last changes, result should come out in a few minutes/hours, but I don't expect the main issue to be resolved.

Maybe if you check the CI logs, you'll understand the issue. To me it could be just similar to some issues I had on other apps which would only show in the dev CI, but everything would be fine on the main one, so maybe it's ok as it is, I don't know at the moment.

Also I [requested the addition of facilmap to the yunohost catalog](https://github.com/YunoHost/apps/pull/1164) (so people can see it in their yunohost admin interface). I chose the category "productivity_and_management" which seemed the most appropriate (or maybe the less inappropriate). If you think another one would be better, maybe suggest it in that PR.

**Comment by cdauth** [comment]
All I can see from the logs is that it looks like the wrong mysql password is passed to the app.

**Comment by eauchat** [comment]
Then maybe the problem is this:
```
./scripts/install:107:db_pwd= # Will be set by facilmap_create_db
./scripts/_common.sh:42:    ynh_mysql_setup_db --db_user=$db_user --db_name=$db_name --db_pwd=$db_pwd
```
Seems that nowhere during install script the $db_pwd variable has been set.

**Comment by cdauth** [comment]
My understanding is that the [ynh_mysql_setup_db](https://github.com/YunoHost/yunohost/blob/dev/data/helpers.d/mysql#L216) function sets the `$db_pwd` variable to a random value if it is empty. I'm not sure what exactly is going on in the CI.

Unfortunately I don't have time to look into this deeper right now, I can find some time in the next days.

**Comment by eauchat** [comment]
Ok, sounds good!

**Comment by eauchat** [comment]
I believe this issue could be closed now, since facilmap now is installable on yunohost. No?
Usually when a new app is available on yunohost, a post to present the app is published on their forum. I can do it if you want, unless you prefer doing it yourself.

**Comment by eauchat** [comment]
I created the [presentation post on yunohost forum](https://forum.yunohost.org/t/facilmap-collaborative-maps-and-routing-with-a-straightforward-interface/17296). If you want to make some modifications to it, tell me, or you can make some comments to it.
I close this issue, but reopen it if you feel it's necessary.
Great that facilmap is now available on yunohost! Thanks for making it possible, and for making facilmap :)
